### ISSUE TITLE
ihx2iic.py broken for python3?

### ISSUE THREAD

**Issue by Vonger** [djmuhlestein/fx2lib#32]
When I run this tool, I get an error:
$ python ihx2iic.py
  File "/e/src/fx2lib/utils/ihx2iic.py", line 35
    raise ValueError, "Length must be even"

I am not very good at Python, is it not compatible for python3?
If so how to fix it :)

**Comment by DanielO** [comment]
Hi,
I have never used the script so I can't really test it, however I ran the Python 2to3 tool over it and got it running.
Please try https://github.com/djmuhlestein/fx2lib/pull/33 and see if it works for you.

Note that I did not touch the other Python scripts - I can't test them right now either..

**Comment by djmuhlestein** [comment]
Merged.
