### ISSUE TITLE
wiki is broken

### ISSUE THREAD

**Issue by elasticdotventures** [djmuhlestein/fx2lib#34]
https://fx2lib.wiki.sourceforge.net/

is down.

**Comment by Ho-Ro** [comment]
use https://sourceforge.net/p/fx2lib/wiki/Home/ instead

**Comment by mcuee** [comment]
Wiki link to the Sourceforge bug/issue tracker is broken.
It is here: https://sourceforge.net/p/fx2lib/issues/

**Comment by djmuhlestein** [comment]
I removed the link altogether.  All there was on the wiki was a link to GitHub which I fixed, but there is no reason to go to that page if you're already on GitHub.
