### ISSUE TITLE
Multiple configuration descriptors

### ISSUE THREAD

**Issue by vpelletier** [djmuhlestein/fx2lib#5]
I'm trying to add a configuration descriptor to a firmware. I belive this is not supported by lib/setupdat.c, as it always returns the descriptor at pDevConfig, which is either highspd_dscr or fullspd_dscr from dscr.a51 .
I've succeeded adding support for several descriptors, but I cannot figure of a backward-compatible way without involving several #ifdef as I require new exports from dscr.a51.

Please review my patch: vpelletier/fx2lib@f98866cc4bb88c0179d3f9c05c77fc2ebecfe2dc .

I'm unsure of intended coding style (indentation especially).

**Comment by mcuee** [comment]
@vpelletier 

I know this is a very old post but your patch link is broken.

**Comment by djmuhlestein** [comment]
@mcuee I'm not sure if the original patch is valid any longer.  I know I have several legacy firmwares that have multiple descriptors.  Are you having a specific issue?  I'm wondering if this issue should have been closed a long time ago but was simply neglected.
